#ifndef LVKW_CONFIG_H_INCLUDED
#define LVKW_CONFIG_H_INCLUDED

#define LVKW_VERSION_MAJOR 0
#define LVKW_VERSION_MINOR 1
#define LVKW_VERSION_PATCH 0

/* Configuration options */
#define LVKW_ENABLE_CONTROLLER
#define LVKW_ENABLE_DIAGNOSTICS
#define LVKW_GATHER_TELEMETRY
#define LVKW_VALIDATE_API_CALLS
/* #undef LVKW_RECOVERABLE_API_CALLS */
/* #undef LVKW_ENABLE_INTERNAL_CHECKS */
/* #undef LVKW_USE_FLOAT */

#endif  // LVKW_CONFIG_H_INCLUDED
